#ifndef BL_OVERLAY_H
#define BL_OVERLAY_H

#define BL_OVERLAY_NONE -1

typedef enum {
    BL_OVERLAY_TYPE_MODE,  //0
    BL_OVERLAY_TYPE_SCENE, //1
    BL_OVERLAY_TYPE_MESS, //2
    BL_OVERLAY_TYPE_MAX //3
} BLOverlayType;


typedef enum {
    BL_OVERLAY_MODE_MG, //0
    BL_OVERLAY_MODE_FIELD, //1
    BL_OVERLAY_MODE_MAX //2
} BLOverlayMode;

typedef enum {
    BL_OVERLAY_SCENE_MG01, //0
    BL_OVERLAY_SCENE_MG02, //1
    BL_OVERLAY_SCENE_MG03, //2
    BL_OVERLAY_SCENE_MG04, //3
    BL_OVERLAY_SCENE_MG05, //4
    BL_OVERLAY_SCENE_MG06, //5
    BL_OVERLAY_SCENE_MG07, //6
    BL_OVERLAY_SCENE_MG08, //7
    BL_OVERLAY_SCENE_MG09, //8
    BL_OVERLAY_SCENE_MG10, //9
    BL_OVERLAY_SCENE_MG11, //10
    BL_OVERLAY_SCENE_MG12, //11
    BL_OVERLAY_SCENE_MG13, //12
    BL_OVERLAY_SCENE_MG14, //13
    BL_OVERLAY_SCENE_MG15, //14
    BL_OVERLAY_SCENE_MG16, //15
    BL_OVERLAY_SCENE_MG17, //16
    BL_OVERLAY_SCENE_MG18, //17
    BL_OVERLAY_SCENE_MG19, //18
    BL_OVERLAY_SCENE_MG20, //19
    BL_OVERLAY_SCENE_MG21, //20
    BL_OVERLAY_SCENE_MG22, //21
    BL_OVERLAY_SCENE_MG23, //22
    BL_OVERLAY_SCENE_MG24, //23
    BL_OVERLAY_SCENE_MG25, //24
    BL_OVERLAY_SCENE_MG26, //25
    BL_OVERLAY_SCENE_MG27, //26
    BL_OVERLAY_SCENE_MG28, //27
    BL_OVERLAY_SCENE_MG29, //28
    BL_OVERLAY_SCENE_MG30, //29
    BL_OVERLAY_SCENE_MG31, //30
    BL_OVERLAY_SCENE_MG32, //31
    BL_OVERLAY_SCENE_MG33, //32
    BL_OVERLAY_SCENE_MG34, //33
    BL_OVERLAY_SCENE_MG35, //34
    BL_OVERLAY_SCENE_MG36, //35
    BL_OVERLAY_SCENE_MG37, //36
    BL_OVERLAY_SCENE_MG38, //37
    BL_OVERLAY_SCENE_MG39, //38
    BL_OVERLAY_SCENE_MG40, //39
    BL_OVERLAY_SCENE_MG41, //40
    BL_OVERLAY_SCENE_MG42, //41
    BL_OVERLAY_SCENE_MG43, //42
    BL_OVERLAY_SCENE_MG44, //43
    BL_OVERLAY_SCENE_MG45, //44
    
    BL_OVERLAY_SCENE_FIELD_STAR, //45
    BL_OVERLAY_SCENE_FIELD_MOON, //46
    BL_OVERLAY_SCENE_FIELD_SUN, //47
    BL_OVERLAY_SCENE_FIELD_EARTH, //48
    
    BL_OVERLAY_SCENE_MAX, //49
} BLOverlayScene;

void BL_OverlayInit(void);
void BL_OverlayLoad(BLOverlayType type, int index);
void BL_OverlayMgLoad(int no);
void BL_OverlayFieldLoad(int no);
void BL_OverlayClose(void);

#endif