#ifndef MAP_DEFS_H
#define MAP_DEFS_H

#define MAPFLAG(type, no) (((type) << 8)|(no))

#define MAP_ITEM_NONE 0

#define MAP_ITEM_BIT(no) (1 << ((no)-1))

enum {
	MAP_QUEST_JACK_BOSS, //0
	MAP_QUEST_QUEEN_BOSS, //1
	MAP_QUEST_CHAR_KEY, //2
	MAP_QUEST_EVIL, //3
	MAP_QUEST_GREEN_KEY, //4
	MAP_QUEST_AO_FLUTE, //5
	MAP_QUEST_AO_BASKETBALL, //6
	MAP_QUEST_AO_ACE_SWIM, //7
	MAP_QUEST_MIDORI_FLUTE, //8
	MAP_QUEST_MIDORI_PUZZLE, //9
	MAP_QUEST_URANAI_AQUA, //10
	MAP_QUEST_URANAI_PRETTY, //11
	MAP_QUEST_PRETTY, //12
	MAP_QUEST_AQUA, //13
};

enum {
	MAP_ZONE_TYPE_STAR, //0
	MAP_ZONE_TYPE_MOON, //1
	MAP_ZONE_TYPE_SUN, //2
	MAP_ZONE_TYPE_EARTH //3
};

enum {
	MAP_AREA_STAR_A1P1, //0
	MAP_AREA_STAR_A1P2, //1
	MAP_AREA_STAR_A1P3, //2
	MAP_AREA_STAR_A1P4, //3
	MAP_AREA_STAR_A2P1, //4
	MAP_AREA_STAR_A2P2, //5
	MAP_AREA_STAR_A2P3, //6
	MAP_AREA_STAR_A2P4, //7
	MAP_AREA_STAR_A2P5, //8
	MAP_AREA_MOON_A1P1, //9
	MAP_AREA_MOON_A1P2, //10
	MAP_AREA_MOON_A1P3, //11
	MAP_AREA_MOON_A1P4, //12
	MAP_AREA_MOON_A1P5, //13
	MAP_AREA_MOON_A2P1, //14
	MAP_AREA_MOON_A2P2, //15
	MAP_AREA_MOON_A2P3, //16
	MAP_AREA_SUN_A1P1, //17
	MAP_AREA_SUN_A1P2, //18
	MAP_AREA_SUN_A1P3, //19
	MAP_AREA_SUN_A1P4, //20
	MAP_AREA_SUN_A2P1, //21
	MAP_AREA_SUN_A2P2, //22
	MAP_AREA_SUN_A2P3, //23
	MAP_AREA_SUN_A2P4, //24
	MAP_AREA_EARTH_A1P1, //25
	MAP_AREA_EARTH_A1P2, //26
	MAP_AREA_EARTH_A1P3, //27
	MAP_AREA_EARTH_A1P4, //28
	MAP_AREA_EARTH_A2P1, //29
	MAP_AREA_EARTH_A2P2, //30
	MAP_AREA_EARTH_A2P3, //31
	MAP_AREA_EARTH_A2P4, //32
	MAP_AREA_EARTH_A2P5, //33
};

enum {
	MAP_CHR_SHIRO, //0
	MAP_CHR_KURO, //1
	MAP_CHR_PRETTY, //2
	MAP_CHR_GOLD, //3
	MAP_CHR_AO, //4
	MAP_CHR_MIDORI, //5
	MAP_CHR_AQUA, //6
	MAP_CHR_STAR, //7
	MAP_CHR_EVIL, //8
	MAP_CHR_BOSS, //9
	MAP_CHR_ZONE1, //10
	MAP_CHR_ZONE2, //11
	MAP_CHR_ZONE3, //12
	MAP_CHR_MAX //13
};

enum {
	MAP_FLAG_NULL, //0
	MAP_FLAG_PLAYER, //1
	MAP_FLAG_STAR_A1P1, //2
	MAP_FLAG_STAR_A1P2, //3
	MAP_FLAG_STAR_A1P3, //4
	MAP_FLAG_STAR_A1P4, //5
	MAP_FLAG_STAR_A2P1, //6
	MAP_FLAG_STAR_A2P2, //7
	MAP_FLAG_STAR_A2P3, //8
	MAP_FLAG_STAR_A2P4, //9
	MAP_FLAG_STAR_A2P5, //10
	MAP_FLAG_MOON_A1P1, //11
	MAP_FLAG_MOON_A1P2, //12
	MAP_FLAG_MOON_A1P3, //13
	MAP_FLAG_MOON_A1P4, //14
	MAP_FLAG_MOON_A1P5, //15
	MAP_FLAG_MOON_A2P1, //16
	MAP_FLAG_MOON_A2P2, //17
	MAP_FLAG_MOON_A2P3, //18
	MAP_FLAG_SUN_A1P1, //19
	MAP_FLAG_SUN_A1P1_ALT, //20
	MAP_FLAG_SUN_A1P2, //21
	MAP_FLAG_SUN_A1P3, //22
	MAP_FLAG_SUN_A1P4, //23
	MAP_FLAG_SUN_A2P1, //24
	MAP_FLAG_SUN_A2P2, //25
	MAP_FLAG_SUN_A2P3, //26
	MAP_FLAG_SUN_A2P4, //27
	MAP_FLAG_EARTH_A1P1, //28
	MAP_FLAG_EARTH_A1P2, //29
	MAP_FLAG_EARTH_A1P3, //30
	MAP_FLAG_EARTH_A1P4, //31
	MAP_FLAG_EARTH_A2P1, //32
	MAP_FLAG_EARTH_A2P2, //33
	MAP_FLAG_EARTH_A2P3, //34
	MAP_FLAG_EARTH_A2P4, //35
	MAP_FLAG_EARTH_A2P5, //36
	MAP_FLAG_PIECE_STAR, //37
	MAP_FLAG_PIECE_MOON, //38
	MAP_FLAG_PIECE_SUN, //39
	MAP_FLAG_PIECE_EARTH, //40
	MAP_FLAG_PIECE_LIGHTNING, //41
	MAP_FLAG_PIECE_RAINBOW, //42
	MAP_FLAG_PIECE_HEART, //43
	MAP_FLAG_PIECE_KEY, //44
	MAP_FLAG_PIECE_TOKEN, //45 
	MAP_FLAG_2E,
	MAP_FLAG_PAD, //47
	MAP_FLAG_MAIL_KURO, //48
	MAP_FLAG_MAIL_PRETTY, //49
	MAP_FLAG_MAIL_GOLD, //50
	MAP_FLAG_MAIL_AO, //51
	MAP_FLAG_MAIL_MIDORI, //52
	MAP_FLAG_MAIL_AQUA, //53
	MAP_FLAG_MAIL_STAR, //54
	MAP_FLAG_MAIL_THIEF, //55
	MAP_FLAG_MAIL_ZAKO, //56
	MAP_FLAG_CHR_SHIRO, //57
	MAP_FLAG_CHR_KURO, //58
	MAP_FLAG_CHR_PRETTY, //59
	MAP_FLAG_CHR_EVIL, //60
	MAP_FLAG_CHR_AO, //61
	MAP_FLAG_CHR_MIDORI, //62
	MAP_FLAG_CHR_GOLD, //63
	MAP_FLAG_MINI, //64
	MAP_FLAG_MAGIC, //65
	MAP_FLAG_BOSS_JACK, //66
	MAP_FLAG_BOSS_QUEEN, //67
	MAP_FLAG_BOSS_ACE, //68
	MAP_FLAG_BOSS_EVIL, //69
	MAP_FLAG_THIEF, //70
	MAP_FLAG_NINJA, //71
	MAP_FLAG_SAGE, //72
	MAP_FLAG_MUMMY, //73
	MAP_FLAG_URANAI, //74
	MAP_FLAG_MG_HYPNOTIZE, //75
	MAP_FLAG_STAR, //76
	MAP_FLAG_MOON, //77
	MAP_FLAG_SUN, //78
	MAP_FLAG_EARTH, //79
	MAP_FLAG_STAMP, //80
	MAP_FLAG_ZONE_VISIT, //81
	MAP_FLAG_ZONE_INFORME_VISIT, //82
	MAP_FLAG_AREA_VISIT, //83
	MAP_FLAG_ZONE_EVIL, //84
	MAP_FLAG_ZONE_ENTER, //85
	MAP_FLAG_ZONE_EXIT, //86
	MAP_FLAG_EVENT, //87
	MAP_FLAG_NEXT_STAMP, //88
	MAP_FLAG_EVENT_TOUCH, //89
	MAP_FLAG_5A,
	MAP_FLAG_BONUS, //91
	MAP_FLAG_5C,
	MAP_FLAG_BONUS2, //93
	MAP_FLAG_5E,
};

enum {
	MAP_ITEM_HEAD, //0
	MAP_ITEM_BODY, //1
	MAP_ITEM_BOMB, //2
	MAP_ITEM_TICKET //3
};

enum {
	MAP_ITEM_HEAD_STAR = 1,
	MAP_ITEM_HEAD_EVIL, //2
	MAP_ITEM_HEAD_FLUTE, //3
	MAP_ITEM_HEAD_PUMPKIN, //4
	MAP_ITEM_HEAD_COWBOY, //5
	MAP_ITEM_HEAD_SAGE, //6
};

enum {
	MAP_ITEM_BODY_STAR_CAPE = 1,
	MAP_ITEM_BODY_EVIL_CAPE, //2
	MAP_ITEM_BODY_FISHING_ROD, //3
	MAP_ITEM_BODY_SWIM_RING, //4
	MAP_ITEM_BODY_BROOM, //5
	MAP_ITEM_BODY_SHURIKEN, //6
	MAP_ITEM_BODY_BROOM_WATER, //7
	MAP_ITEM_BODY_BROOM_FIRE, //8
};

enum {
	MAP_ITEM_BOMB_NORMAL = 1,
	MAP_ITEM_BOMB_SOCCER, //2
	MAP_ITEM_BOMB_BASKETBALL, //3
	MAP_ITEM_BOMB_POT, //4
	MAP_ITEM_BOMB_MINI, //5
	MAP_ITEM_BOMB_MAGNET, //6
	MAP_ITEM_BOMB_WATER, //7
	MAP_ITEM_BOMB_FIRE, //8
};

enum {
	MAP_ITEM_TICKET_TRUCK = 1,
	MAP_ITEM_TICKET_SUNJET, //2
	MAP_ITEM_TICKET_SOCCER, //3
	MAP_ITEM_TICKET_BASKETBALL, //4
	MAP_ITEM_TICKET_FISHING, //5
	MAP_ITEM_TICKET_DANCE, //6
	MAP_ITEM_TICKET_CYCLE, //7
	MAP_ITEM_TICKET_SUMO, //8
};

enum {
	MAP_ATRC_FLAG_COMPLETE, //0
	MAP_ATRC_FLAG_DEFEAT, //1
	MAP_ATRC_FLAG_COMPLETE_TOKEN, //2
	MAP_ATRC_FLAG_UNK, //3
};

enum {
	MAP_BHOUSE_FLAG_COMPLETE, //0
	MAP_BHOUSE_FLAG_DEFEAT, //1
	MAP_BHOUSE_FLAG_UNK //2
};

enum {
	MAP_MAIL_NULL, //0
	MAP_MAIL_MAX = 84,
};

#endif