#ifndef _NNS_GFX_TRANSFER_H
#define _NNS_GFX_TRANSFER_H

#include <nitro/types.h>

typedef enum {
    NNS_GFX_TRANSFER_TEX, //0
    NNS_GFX_TRANSFER_TEX_PLTT, //1
    NNS_GFX_TRANSFER_CLEAR_IMAGE, //2
    NNS_GFX_TRANSFER_CLEAR_DEPTH, //3
    NNS_GFX_TRANSFER_BG0_CHAR, //4
    NNS_GFX_TRANSFER_BG1_CHAR, //5
    NNS_GFX_TRANSFER_BG2_CHAR, //6
    NNS_GFX_TRANSFER_BG3_CHAR, //7
    NNS_GFX_TRANSFER_BG0_SCR, //8
    NNS_GFX_TRANSFER_BG1_SCR, //9
    NNS_GFX_TRANSFER_BG2_SCR, //10
    NNS_GFX_TRANSFER_BG3_SCR, //11
    NNS_GFX_TRANSFER_BG2_AFFINE_SCR, //12
    NNS_GFX_TRANSFER_BG3_AFFINE_SCR, //13
    NNS_GFX_TRANSFER_OBJ_PLTT, //14
    NNS_GFX_TRANSFER_BG_PLTT, //15
    NNS_GFX_TRANSFER_OBJ_EXT_PLTT, //16
    NNS_GFX_TRANSFER_BG_EXT_PLTT, //17
    NNS_GFX_TRANSFER_OAM, //18
    NNS_GFX_TRANSFER_OBJ, //19
    NNS_GFX_TRANSFER_SUB_BG0_CHAR, //20
    NNS_GFX_TRANSFER_SUB_BG1_CHAR, //21
    NNS_GFX_TRANSFER_SUB_BG2_CHAR, //22
    NNS_GFX_TRANSFER_SUB_BG3_CHAR, //23
    NNS_GFX_TRANSFER_SUB_BG0_SCR, //24
    NNS_GFX_TRANSFER_SUB_BG1_SCR, //25
    NNS_GFX_TRANSFER_SUB_BG2_SCR, //26
    NNS_GFX_TRANSFER_SUB_BG3_SCR, //27
    NNS_GFX_TRANSFER_SUB_BG2_AFFINE_SCR, //28
    NNS_GFX_TRANSFER_SUB_BG3_AFFINE_SCR, //29
    NNS_GFX_TRANSFER_SUB_OBJ_PLTT, //30
    NNS_GFX_TRANSFER_SUB_BG_PLTT, //31
    NNS_GFX_TRANSFER_SUB_OBJ_EXT_PLTT, //32
    NNS_GFX_TRANSFER_SUB_BG_EXT_PLTT, //33
    NNS_GFX_TRANSFER_SUB_OAM, //34
    NNS_GFX_TRANSFER_SUB_OBJ, //35
} NNSGfxTransferType;

typedef struct {
    NNSGfxTransferType type;
    void *buf;
    u32 ofs;
    u32 size;
} NNSGfxTransfer;

void NNS_GfxTransferInit(NNSGfxTransfer *transferBuf, int maxTransfers);
void NNS_GfxTransferExec(void);
BOOL NNS_GfxTransferAdd(NNSGfxTransferType type, u32 ofs, void *buf, u32 size);

#endif